* RateGravity Takehome
** Installation
   After you've enter the cloned directory, enter the following:
   #+BEGIN_SRC sh :results output
   npm i
   #+END_SRC
** Build and Deploy
   Create a .env file at the root of your newly cloned directory. Set the attirbute API_KEY to your respective key.
   #+BEGIN_EXAMPlE :results output
   API_KEY=*YOUR_KEY_HERE*
   #+END_EXAMPLE


   Build the application by entering the following:
   #+BEGIN_SRC sh :results output
   npm run build
   #+END_SRC

   Finally, spin up the site with the following:
   #+BEGIN_SRC sh :results output
   npm start
   #+END_SRC
   And navigate to localhost:8000
** Testing and More
   To run the test suite enter the following:
   #+BEGIN_SRC sh :results output
   npm test
   #+END_SRC

   If you'd like to make live changes to the code you can enable hot reloading with the following:
   #+BEGIN_SRC sh :results output
   npm run devpack
   #+END_SRC
 
** Library Breakdown
   In broad strokes
   - Frontend
     - Redux Saga : Redux middleware for side effects. Used for API requests
     - CSS/Style loader : Used to collect and inject CSS into React
   - Testing
     - Enzyme : Testing utility that makes React testing much simpler.
     - JSDom : JS emulating DOM. Used with Enzyme to mount React components for testing.
     - Sinon : Testing utility for stub, mocks, etc. Used to help test.
     - Redux Sage Test Plan : Used to help test Sagas in a easier, more readable fashion.
     - Mocha/Chai : Common testing framework and assertion library, respectively. Used to run tests.
   - Backend
     - Express : Mostly just used because I'm familiar with it. Used to serve bundle.
       
